version: "3.8"
services:
  db:
    container_name: "db"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
    command: >
      postgres -c ssl=on
               -c ssl_cert_file=/var/lib/postgresql/certs/server.crt
               -c ssl_key_file=/var/lib/postgresql/certs/server.key
  redis:
    container_name: "redis"
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
    networks:
      - custom
networks:
  custom:
    driver: bridge
